### ISSUE TITLE
Výpis seznamu přihlášek s detaily v GUI

### ISSUE THREAD

**Issue by xkureck** [CESNET/perun-web-apps#144]
Michal Prochazka: Prosím o vytvoření stránky nebo pohledu v GUI, kde budou vypsány přihlášky, ale se všemi detaily. Stejně jako u seznamu podaných přihlášek mít možnost seznam vyexportovat.

**Comment by Vojtech-Sassmann** [comment]
The data should be exported in the excel format and one line should represent one application. The first columns should contain data from the application itself. They should be followed up by the applicationData. For each field of the application, there should be one column.

**Comment by Vojtech-Sassmann** [comment]
And one more note. The columns with the data from the applicationData objects should contain also the name of the field. The format of data of all applications might vary depending on the lifecycle of the application form.
