### ISSUE TITLE
Dialog scrollable content

### ISSUE THREAD

**Issue by Vojtech-Sassmann** [CESNET/perun-web-apps#270]
* Some of the dialogs have to high content, and it can't be displayed on the screen. And there is even a bigger problem. Since we disabled the closing of dialogs by any other way than just clicking the close button, those too high dialogs can't also be closed.
* It would be reasonable to handle this problematic globally, maybe it would be enough to declare some properties to a CSS class that is used for the dialog content?

**Comment by xkostka2** [comment]
Could you provide some concrete example?
