### ISSUE TITLE
Change object name/description in detail of object

### ISSUE THREAD

**Issue by xkureck** [CESNET/perun-web-apps#328]
In Facility/Resource/Group/Vo detail there should be (probably right next to the name of entity) some edit icon which would pop some edit dialog. Should work the same as in old gui.

**Comment by saksham93** [comment]
Hi,
I wish to work on this issue.
Thanks

**Comment by Vojtech-Sassmann** [comment]
> Hi,
> I wish to work on this issue.
> Thanks

Hi @saksham93, this issue might be a bit challenging for you without some more of our internal information

**Comment by Vojtech-Sassmann** [comment]
Hi @saksham93, if you would like to work on this issue, I could provide you with some further information.

For now, this issue would be relevant for updates of vos, facilities, and resources. 
* Vo 
  * in the dialog there should be a short name displayed (but not possible to edit)
  * Full name - this should be possible to update
  * To update the vo, you can use the VosManagerService/updateVo
* Facility
  * It should be possible to update name and description
  * To update the facility, you can use the FacilitiesManagerService/updateFacility
* Resource
  * It should be possible to update name and description
  * To update the resource, you can use the ResourcesManagerService/updateResource

Please let me know if you still wish to work on this issue.
