### ISSUE TITLE
group - members - search field too short

### ISSUE THREAD

**Issue by xkureck** [CESNET/perun-web-apps#330]
In the search field for members the search field is too short and the description of the field doesnt fit into the field.
Make the search field wider and also make sure the description text fit the field.

**Comment by saksham93** [comment]
Hi,
I wish to work on this issue.
Thanks

**Comment by saksham93** [comment]
Hi @xkureck - I am new to this project. Can you please elaborate on which page this search bar is and how to login to portals on dev? Thank you.

**Comment by Vojtech-Sassmann** [comment]
Hi @saksham93. Sorry for the late response. We have updated the README file and it should be now easier for you to run the project.

You need to fetch new changes from this repository and then follow the `How to serve the AdminGUI` part in the README file.
With these changes, no login portal should appear and you should be directly logged in with the default user.

To find the search bar, select some virtual organization, go to groups, select a group, and go to members.

I hope this info will help you.

**Comment by saksham93** [comment]
@Vojtech-Sassmann Thank you for the clarification. I have raised the PR which addresses this issue.
