### ISSUE TITLE
Redirect to a VO detail after creating the VO

### ISSUE THREAD

**Issue by balcirakpeter** [CESNET/perun-web-apps#350]
I'm always frustrated when I create a VO and then I have to find that VO on the list again.

It would be nice if there is a redirection to the VO detail after the VO creation.

Another solution could be to add the newly created VO to the beginning of the list (as recently created or something like that).

**Actual situation:**
![image](https://user-images.githubusercontent.com/17315935/87135297-26cde000-c29a-11ea-92e9-799f151bfd6e.png)
![image](https://user-images.githubusercontent.com/17315935/87135483-609ee680-c29a-11ea-9e00-2a76070a87d0.png)

**Desired solution:**
![image](https://user-images.githubusercontent.com/17315935/87135297-26cde000-c29a-11ea-92e9-799f151bfd6e.png)
![image](https://user-images.githubusercontent.com/17315935/87135579-875d1d00-c29a-11ea-8111-11b48a4a6aad.png)

**Alternative solution:**
![image](https://user-images.githubusercontent.com/17315935/87135297-26cde000-c29a-11ea-92e9-799f151bfd6e.png)
![image](https://user-images.githubusercontent.com/17315935/87135638-99d75680-c29a-11ea-83a0-fb4b005274b5.png)

**Comment by xkureck** [comment]
I like the second solution(adding newly created vo into recently viewed) more. I would suggest doing it this way.

**Comment by Vojtech-Sassmann** [comment]
I think the solution with the redirect might be better because when someone creates a vo, he/she probably wants to do something with it. The other solution would be better if most of the users would create multiple vos at the same time and didn't want to do anything with it, which is unlikely. But I am also ok with this other solution.
