### ISSUE TITLE
Set member expiration date and show and set expiration date for member's groups

### ISSUE THREAD

**Issue by xkureck** [CESNET/perun-web-apps#382]
Right now we are only showing membership status and expiration date(for vo) in the members overview. (and tbh not in very nice way)
Now we want to change member expiration date. Find out where would this feature would be positioned in our gui(so it make sense). 
Also now we want to show somewhere expiration date and status of member in his groups. With that we also want to change the member status in group. Find out where would this feature would be positioned in our gui. For that Vojta/Slavek advice would be nice I guess

**Comment by Vojtech-Sassmann** [comment]
Hi @xkureck, recently, we had with @licehammer discussion about membership statuses.

First thing is that we want to rename the `VALID` status to `ACTIVE`. This will be only changed in GUI. In the member object the value will be still `VALID`. We also want to change `EXPIRED` to `INACTIVE`. Again, this will be changed only in gui.

Next thing, we want to show users only one status on the group members overview page (not one for vo and one for group). In the member object, you should receive the member's group status. 
  * If it is `VALID` you have to check if the vo status is also `VALID`. If so, you show the `VALID (now ACTIVE)` status.  If it is anything other than valid, you show the `EXPIRED (now INACTIVE) status`. 
  * If the group status is `EXPIRED` you show the `INACTIVE` status.

Also, if the user would hover over the status (or click on it) it would be nice if it would show something like this:
| Status: INACTIVE          |
|---------------------------------|
| Vo status: INACTIVE     |
| Group status: ACTIVE   |
